// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getDummyItems = `-- name: GetDummyItems :many
SELECT id, name FROM dummy
`

func (q *Queries) GetDummyItems(ctx context.Context) ([]Dummy, error) {
	rows, err := q.db.Query(ctx, getDummyItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dummy
	for rows.Next() {
		var i Dummy
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
